ci: add jlumbroso/free-disk-space

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -14,6 +14,26 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # Sporadic error: "  cargo:warning=rocksdb/db/db_impl/db_impl_secondary.cc:684:1: fatal error: error writing to /tmp/ccnRl4w5.s: No space left on device"
+      # Sometimes work depending on version, OS, etc.
+      - name: Free Disk Space (Ubuntu)
+        uses: jlumbroso/free-disk-space@main
+        with:
+          # this might remove tools that are actually needed,
+          # if set to "true" but frees about 6 GB
+          tool-cache: false
+          # all of these default to true, but feel free to set to
+          # "false" if necessary for your workflow
+          android: true
+          dotnet: true
+          haskell: true
+          large-packages: true
+          swap-storage: true
+      # TODO or easier: "large-packages: false" above?
+      - name: re-add needed packages
+        run: |
+          sudo apt-get install -y libclang-dev
+
       - uses: Interstellar-Network/gh-actions/prepare@v3-dev
         with:
           ssh_key_input: ${{ secrets.SSH_KEY_MACHINE_USER_INTERSTELLAR_CI }}
@@ -53,6 +73,16 @@ jobs:
       - name: cargo test --release
         run: |
           cargo test --release
+
+      # TODO move into separate action? ideally into a JS action "post" that setup ccache?
+      # NOTE: remove if using "rust-build-and-test"
+      - name: Print ccache/sccache stats
+        # display stats even if tests failed
+        if: success() || failure()
+        run: |
+          ccache --show-stats || echo "ccache not found!"
+          sccache --show-stats || echo "ccache sccache found!"
+        shell: bash
 
   ##########################################################################
   ##########################################################################
